#!/usr/bin/env bash
mkdir -p /opt/fxcommander
cp -v ./fxcommander /opt/fxcommander/fxcommander
cp -v ./version /opt/fxcommander/version
cp -v ./dependencies /opt/fxcommander/dependencies
chmod +x /opt/fxcommander/fxcommander
cp -v ./*.css /opt/fxcommander

chmod 777 -R /opt/fxcommander

rm -fv /usr/local/bin/fxcommander
ln -s /opt/fxcommander/fxcommander /usr/local/bin/fxcommander

echo "fxcommander installed."
