#!/usr/bin/env bash
mkdir -p /opt/fxcommander
cp -v ./fxcommander /opt/fxcommander/fxcommander
chmod +x /opt/fxcommander/fxcommander
#cp -vr ./images /opt/fxcommander/images
cp -v ./*.css /opt/fxcommander

chmod 777 -R /opt/fxcommander

rm -fv /usr/local/bin/fxcommander
ln -s /opt/fxcommander/fxcommander /usr/local/bin/fxcommander

echo "fxcommander installed."
